name: Build client

on:
  push:
    paths:
      - "Client/**"

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Caching library
        uses: actions/cache@v2
        with:
          path: Client/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Building Unity project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Client
          unityVersion: 2020.3.2f1
          buildsPath: build/

      - name: Compress build
        run: zip -r Client-${{ matrix.targetPlatform }} build/${{ matrix.targetPlatform }}

      - name: Upload Release Assets
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Client Development Build"
          files: Client-${{ matrix.targetPlatform }}.zip