name: Build client

on:
  push:
    paths:
      - "Client/**"

jobs:
  createClientRelease:
    name: Updates the client release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Client Development Build
          draft: false
          prerelease: true



  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: createClientRelease
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Caching library
        uses: actions/cache@v2
        with:
          path: Client/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Building Unity project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Client
          unityVersion: 2020.3.2f1
          buildsPath: build/

      - name: Compress build
        run: zip -r Client-${{ matrix.targetPlatform }} build/${{ matrix.targetPlatform }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createClientRelease.outputs.upload_url }}
          asset_path: ./Client-${{ matrix.targetPlatform }}.zip
          asset_name: Client-${{ matrix.targetPlatform }}.zip
          asset_content_type: application/zip